server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: kafka
          uri: http://127.0.0.1:9092
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
        - id: es
          uri: http://127.0.0.1:9200
          predicates:
            - Path=/es/**
          filters:
            - StripPrefix=1
        - id: event
          uri: http://127.0.0.1:8050
          predicates:
            - Path=/event/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: info