server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: kafka
          uri: http://127.0.0.1:9092
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: debug