server:
  port: 6650
spring:
  application:
    name: learning-spring-pulsar
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "dev-learning-spring-common"
pulsar:
  service-url: pulsar://192.168.2.25:6650