db-host:
db-user:
db-pass: 
server:
  port: 3306

spring:
  application:
    name: learning-mybatis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db-host}:3306/demo?user=${db-user}&password=${db-pass}&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true&useCursorFetch=true&rewriteBatchedStatements=true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-test-query: select 1
      connection-timeout: 30000
  data:
    mongodb:
      uri: mongodb://${db-user}:${db-pass}@${db-host}:27017/erp_local?authSource=admin

mybatis:
  mapper-locations: classpath*:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.jdbc.core: debug
    com.learning.db.mapper: debug