server:
  port: 6379

spring:
  application:
    name: learning-spring-cache
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "dev-learning-spring-common"
  redis:
    cluster:
      nodes: 192.168.2.18:7000,192.168.2.18:7001,192.168.2.18:7002
    password: ${db-pass}